/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShippingTermsRouteImport } from './routes/shippingTerms'
import { Route as BillingTermsRouteImport } from './routes/billingTerms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'

const AboutLazyRouteImport = createFileRoute('/about')()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const ShippingTermsRoute = ShippingTermsRouteImport.update({
  id: '/shippingTerms',
  path: '/shippingTerms',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingTermsRoute = BillingTermsRouteImport.update({
  id: '/billingTerms',
  path: '/billingTerms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billingTerms': typeof BillingTermsRoute
  '/shippingTerms': typeof ShippingTermsRoute
  '/about': typeof AboutLazyRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billingTerms': typeof BillingTermsRoute
  '/shippingTerms': typeof ShippingTermsRoute
  '/about': typeof AboutLazyRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billingTerms': typeof BillingTermsRoute
  '/shippingTerms': typeof ShippingTermsRoute
  '/about': typeof AboutLazyRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billingTerms'
    | '/shippingTerms'
    | '/about'
    | '/customers/$customerId'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billingTerms'
    | '/shippingTerms'
    | '/about'
    | '/customers/$customerId'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/billingTerms'
    | '/shippingTerms'
    | '/about'
    | '/customers/$customerId'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingTermsRoute: typeof BillingTermsRoute
  ShippingTermsRoute: typeof ShippingTermsRoute
  AboutLazyRoute: typeof AboutLazyRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shippingTerms': {
      id: '/shippingTerms'
      path: '/shippingTerms'
      fullPath: '/shippingTerms'
      preLoaderRoute: typeof ShippingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billingTerms': {
      id: '/billingTerms'
      path: '/billingTerms'
      fullPath: '/billingTerms'
      preLoaderRoute: typeof BillingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingTermsRoute: BillingTermsRoute,
  ShippingTermsRoute: ShippingTermsRoute,
  AboutLazyRoute: AboutLazyRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
